#!/usr/bin/with-contenv bash

  ### Adjust NGINX Runtime Variables
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  sed -i -e "s/<VIRTUAL_HOST>/$VIRTUAL_HOST/g" /etc/nginx/conf.d/default.conf
   
   if [ -f /assets/jitsi-meet/config.js ] ; then
        echo '** Custom Jitsi Meet config.js Found'
        cp -R /assets/jitsi-meet/config.js /etc/jitsi/meet/config.js
   else
	cat  > /etc/jitsi/meet/$VIRTUAL_HOST-config.js <<EOF;
var config = { 
    hosts: {
        domain: '$VIRTUAL_HOST',
        muc: 'conference.$VIRTUAL_HOST', 
        bridge: 'jitsi-videobridge.$VIRTUAL_HOST'
    },
    useNicks: false,
    bosh: '//$VIRTUAL_HOST/http-bind', 
};
EOF
   fi

   if [ -d /assets/jitsi-meet ]; then
        cp -R /assets/jitsi-meet/* /usr/share/jitsi-meet/
        chown -R www-data /usr/share/jitsi-meet
   fi

mkdir -p /tmp/state/
touch /tmp/state/10-nginx-init
