#!/usr/bin/with-contenv bash

cat  > /etc/jitsi/videobridge/config <<EOF; 
JVB_HOSTNAME=$VIRTUAL_HOST
JVB_HOST=
JVB_PORT=5347
JVB_SECRET=$JITSI_VIDEO_PASS
JVB_OPTS=""

JAVA_SYS_PROPS="$JVB_EXTRA_JVM_PARAMS -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/www/logs/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties"
EOF

cat  > /etc/jitsi/videobridge/log4j2.xml <<EOF; 
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Properties>
    <Property name="log-path">/www/logs/jitsi</Property>
  </Properties>
    <Appenders>
        <RollingFile name="RollingFile" fileName="${log-path}/cs.log"
                 filePattern="${log-path}/$${date:yyyy-MM}/cs-%d{MM-dd-yyyy}-%i.log.gz">
      <PatternLayout pattern="%d %-5p (%F:%L) - %m%n"/>
          <Policies>
            <TimeBasedTriggeringPolicy />
            <SizeBasedTriggeringPolicy size="250 MB"/>
          </Policies>
      </RollingFile>
      <!-- 
      <Console name="STDOUT" target="SYSTEM_OUT">
          <PatternLayout pattern="%d %-5p (%F:%L) - %m%n"/>
      </Console>
       -->
    </Appenders>
    <Loggers>
      <!--<Logger name="org.apache.log4j.xml" level="debug"/>-->
      <Logger name="org.apache.log4j.xml" level="info"/>
        <Root level="info">
            <AppenderRef ref="RollingFile"/>
           <!--  <AppenderRef ref="STDOUT"/>  -->
        </Root>
    </Loggers>
</Configuration>

<!-- 
-Dlog4j.configurationFile=config/log4j2.xml has to be used in VM args
 -->
EOF

cat  > /etc/jitsi/videobridge/logging.properties <<EOF; 
handlers= java.util.logging.ConsoleHandler
#handlers= java.util.logging.ConsoleHandler, com.agafua.syslog.SyslogHandler

java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = net.java.sip.communicator.util.ScLogFormatter

net.java.sip.communicator.util.ScLogFormatter.programname=JVB

.level=INFO

org.jitsi.videobridge.xmpp.ComponentImpl.level=FINE

# All of the INFO level logs from MediaStreamImpl are unnecessary in the context of jitsi-videobridge.
org.jitsi.impl.neomedia.MediaStreamImpl.level=WARNING

# Syslog(uncomment handler to use)
com.agafua.syslog.SyslogHandler.transport = udp
com.agafua.syslog.SyslogHandler.facility = local0
com.agafua.syslog.SyslogHandler.port = 514
com.agafua.syslog.SyslogHandler.hostname = localhost
com.agafua.syslog.SyslogHandler.formatter = net.java.sip.communicator.util.ScLogFormatter
com.agafua.syslog.SyslogHandler.escapeNewlines = false

# to disable double timestamps in syslog uncomment next line
#net.java.sip.communicator.util.ScLogFormatter.disableTimestamp=true

EOF

## Get Container and Public IP for NAT
PUBLIC_IP_ADDRESS=`dig +short $VIRTUAL_HOST @resolver1.opendns.com | tail -n 1`
LOCAL_IP_ADDRESS=`/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1`

echo 'org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.'$VIRTUAL_HOST'/.*' > /etc/jitsi/videobridge/sip-communicator.properties
echo 'org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false' >> /etc/jitsi/videobridge/sip-communicator.properties
echo 'org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS='$LOCAL_IP_ADDRESS >> /etc/jitsi/videobridge/sip-communicator.properties 
echo 'org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS='$PUBLIC_IP_ADDRESS >> /etc/jitsi/videobridge/sip-communicator.properties
echo 'org.jitsi.videobridge.SINGLE_PORT_HARVESTER_PORT=10000' >> /etc/jitsi/videobridge/sip-communicator.properties
echo 'org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=stun.l.google.com:19302' >> /etc/jitsi/videobridge/sip-communicator.properties
mkdir -p /root/.sip-communicator
ln -s /root/.sip-communicator/sip-communicator.properites /etc/jitsi/videobridge/sip-communicator.properties


mkdir -p /tmp/state/
touch /tmp/state/30-jitsi-videobridge-init