#!/usr/bin/with-contenv bash

cat  > /etc/jitsi/videobridge/config <<EOF; 
JVB_HOSTNAME=$VIRTUAL_HOST
JVB_HOST=
JVB_PORT=5347
JVB_SECRET=$JITSI_VIDEO_PASS
JVB_OPTS=""

JAVA_SYS_PROPS="$JVB_EXTRA_JVM_PARAMS -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/www/logs/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties"
EOF

## Get Container and Public IP for NAT
PUBLIC_IP_ADDRESS=`dig +short $VIRTUAL_HOST @resolver1.opendns.com | tail -n 1`
LOCAL_IP_ADDRESS=`/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1`

#echo 'org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.'$VIRTUAL_HOST'/.*' > /etc/jitsi/videobridge/sip-communicator.properties
echo 'org.jitsi.impl.neomedia.transform.srtp.SRTPCryptoContext.checkReplay=false' >> /etc/jitsi/videobridge/sip-communicator.properties
echo 'org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS='$LOCAL_IP_ADDRESS >> /etc/jitsi/videobridge/sip-communicator.properties 
echo 'org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS='$PUBLIC_IP_ADDRESS >> /etc/jitsi/videobridge/sip-communicator.properties
echo 'org.jitsi.videobridge.SINGLE_PORT_HARVESTER_PORT=10000' >> /etc/jitsi/videobridge/sip-communicator.properties
echo 'org.ice4j.ice.harvest.STUN_MAPPING_HARVESTER_ADDRESSES=stun.l.google.com:19302' >> /etc/jitsi/videobridge/sip-communicator.properties
mkdir -p /root/.sip-communicator
cp /etc/jitsi/videobridge/sip-communicator.properties /root/.sip-communicator/
cp -R /root/.sip-communicator /usr/share/jitsi-videobridge/

mkdir -p /tmp/state/
touch /tmp/state/30-jitsi-videobridge-init
