#!/usr/bin/with-contenv bash

if [ ! -f /tmp/state/10-nginx-init ]; then
  sleep 1
fi

if [ ! -f /tmp/state/10-nginx ]; then
	mkdir -p /www/logs/nginx
	mkdir -p /tmp/nginx
  chown -R www-data /www/logs/nginx
	chown www-data /tmp/nginx
  mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** [jitsi-meet] Starting nginx..'
exec nginx
