#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/20-* ]
do
  sleep 1
done

if [ ! -f /tmp/state/30-jitsi-videobridge ]; then

cat  > /etc/jitsi/videobridge/config <<EOF;	
JVB_HOSTNAME=$VIRTUAL_HOST
JVB_HOST=
JVB_PORT=5347
JVB_SECRET=$JITSI_VIDEO_PASS
JVB_OPTS=""

JAVA_SYS_PROPS="$JVB_EXTRA_JVM_PARAMS -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/www/logs/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties"
EOF

cat  > /etc/jitsi/videobridge/log4j2.xml <<EOF;	
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Properties>
		<Property name="log-path">/www/logs/jitsi</Property>
	</Properties>
    <Appenders>
        <RollingFile name="RollingFile" fileName="${log-path}/cs.log"
                 filePattern="${log-path}/$${date:yyyy-MM}/cs-%d{MM-dd-yyyy}-%i.log.gz">
			<PatternLayout pattern="%d %-5p (%F:%L) - %m%n"/>
      		<Policies>
        		<TimeBasedTriggeringPolicy />
        		<SizeBasedTriggeringPolicy size="250 MB"/>
      		</Policies>
    	</RollingFile>
    	<!-- 
    	<Console name="STDOUT" target="SYSTEM_OUT">
      		<PatternLayout pattern="%d %-5p (%F:%L) - %m%n"/>
    	</Console>
    	 -->
    </Appenders>
    <Loggers>
    	<!--<Logger name="org.apache.log4j.xml" level="debug"/>-->
    	<Logger name="org.apache.log4j.xml" level="info"/>
        <Root level="info">
            <AppenderRef ref="RollingFile"/>
           <!--  <AppenderRef ref="STDOUT"/>  -->
        </Root>
    </Loggers>
</Configuration>

<!-- 
-Dlog4j.configurationFile=config/log4j2.xml has to be used in VM args
 -->
EOF

cat  > /etc/jitsi/videobridge/logging.properties <<EOF;	
handlers= java.util.logging.ConsoleHandler
#handlers= java.util.logging.ConsoleHandler, com.agafua.syslog.SyslogHandler

java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = net.java.sip.communicator.util.ScLogFormatter

net.java.sip.communicator.util.ScLogFormatter.programname=JVB

.level=INFO

org.jitsi.videobridge.xmpp.ComponentImpl.level=FINE

# All of the INFO level logs from MediaStreamImpl are unnecessary in the context of jitsi-videobridge.
org.jitsi.impl.neomedia.MediaStreamImpl.level=WARNING

# Syslog(uncomment handler to use)
com.agafua.syslog.SyslogHandler.transport = udp
com.agafua.syslog.SyslogHandler.facility = local0
com.agafua.syslog.SyslogHandler.port = 514
com.agafua.syslog.SyslogHandler.hostname = localhost
com.agafua.syslog.SyslogHandler.formatter = net.java.sip.communicator.util.ScLogFormatter
com.agafua.syslog.SyslogHandler.escapeNewlines = false

# to disable double timestamps in syslog uncomment next line
#net.java.sip.communicator.util.ScLogFormatter.disableTimestamp=true

EOF

cat  > /etc/jitsi/videobridge/sip-communicator.properties <<EOF;	
org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=focus@auth.$VIRTUAL_HOST/.*
EOF

    mkdir -p /www/logs/jitsi
    chgrp -R jitsi /www/logs/jitsi
    chgrp -R jitsi /etc/jitsi
    mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/30-jitsi-videobridge
fi

echo ''
echo '** Starting jitsi-videobridge'
#exec /usr/share/jitsi-videobridge/jvb.sh --host=localhost --domain=$VIRTUAL_HOST --port=5347 --secret=$JITSI_VIDEO_PASS
. /etc/jitsi/videobridge/config
sudo -u jvb JAVA_SYS_PROPS="$JVB_EXTRA_JVM_PARAMS -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/www/logs/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties" /usr/share/jitsi-videobridge/jvb.sh --host=localhost --domain=$JVB_HOSTNAME --port=$JVB_PORT --secret=$JVB_SECRET $JVB_OPTS < /dev/null >> /www/logs/jitsi/jvb.log 2>&1
