#!/usr/bin/with-contenv bash

if [ ! -f /tmp/state/30-jitsi-videobridge-init ]; then
  sleep 1
fi

if [ ! -f /tmp/state/30-jitsi-videobridge ]; then
    mkdir -p /www/logs/jitsi
    chgrp -R jitsi /www/logs/jitsi
    chgrp -R jitsi /etc/jitsi
    mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/30-jitsi-videobridge
fi

echo ''
echo '** [jitsi-videobridge] Starting jitsi-videobridge'
exec sudo -u jvb /usr/share/jitsi-videobridge/jvb.sh --host=localhost --domain=$VIRTUAL_HOST --port=5347 --secret=$JITSI_VIDEO_PASS
sleep 86400
. /etc/jitsi/videobridge/config
#sudo -u jvb JAVA_SYS_PROPS="$JVB_EXTRA_JVM_PARAMS -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=videobridge -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/www/logs/jitsi -Djava.util.logging.config.file=/etc/jitsi/videobridge/logging.properties" /usr/share/jitsi-videobridge/jvb.sh --host=localhost --domain=$JVB_HOSTNAME --port=$JVB_PORT --secret=$JVB_SECRET $JVB_OPTS < /dev/null >> /www/logs/jitsi/jvb.log 2>&1
