#!/usr/bin/with-contenv bash

if [ ! -f /tmp/state/20-prosody-init ]; then
  sleep 1
fi

if [ ! -f /tmp/state/20-prosody ]; then
    echo '** [prosody] Registering Focus User'
	sudo -u prosody prosodyctl register focus auth.$VIRTUAL_HOST $JICOFO_USER_PASS
    
	mkdir -p /www/logs/prosody
    chown -R prosody /www/logs/prosody
    mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/20-prosody
fi

echo ''
echo '** [prosody] Starting prosody'
exec s6-setuidgid prosody prosodyctl start
