#!/usr/bin/with-contenv bash

if [ ! -f /tmp/state/30-jitsi-videobridge ]; then
  sleep 1
fi

if [ ! -f /tmp/state/40-jicofo ]; then
sleep 7
    mkdir -p /www/logs/jitsi
    chgrp -R jitsi /www/logs/jitsi
    chgrp -R jitsi /etc/jitsi
    mkdir -p /tmp/state
    echo 'Initialization Complete' >/tmp/state/40-jicofo
fi

echo ''
echo '** [jicofo] Starting jicofo'
. /etc/jitsi/jicofo/config
#sudo -u jicofo JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/etc/jitsi -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=jicofo -Dnet.java.sip.communicator.SC_LOG_DIR_LOCATION=/www/logs/jitsi -Djava.util.logging.config.file=/etc/jitsi/jicofo/logging.properties" /usr/share/jicofo/jicofo.sh --host=localhost --domain=$VIRTUAL_HOST --secret=$JICOFO_PASS --user_domain=auth.$VIRTUAL_HOST --user_name=focus --user_password=$JICOFO_USER_PASS < /dev/null >> /www/logs/jitsi/jicofo.log 2>&1
/usr/share/jicofo/jicofo.sh --host=localhost --domain=$VIRTUAL_HOST --secret=$JICOFO_PASS --user_domain=auth.$VIRTUAL_HOST --user_name=focus --user_password=$JICOFO_USER_PASS
