#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-nginx-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nginx ]; then
	mkdir -p /www/logs/nginx
	mkdir -p /tmp/nginx
	chown -R jitsi /www/logs/nginx
	chown jitsi /tmp/nginx
	mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** [jitsi-meet] Starting nginx..'
exec nginx
